name = "LuxorGraphPlot"
uuid = "1f49bdf2-22a7-4bc4-978b-948dc219fbbc"
authors = ["GiggleLiu <cacate0129@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
